name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.202'

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: make setup

    - name: Lint
      run: make lint

    - name: Build & Package
      run: make

    - name: Test
      run: make test

    - name: Codecov Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests

    - name: Push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        rm artifacts/WebTty.Exec.*.nupkg
        dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.FEEDZ_IO_TOKEN }} --source https://f.feedz.io/nvd/webtty/nuget/index.json --skip-duplicate
